### ISSUE TITLE
Sink is not a member of "Event<T, E>"

### ISSUE THREAD

**Issue by gtokman** [alexito4/RACPhotos#1]
I tried compiling my project after installing the RacPhotos Pod. I get compiler errors every time I build. Do I have to write an Extension on the Enum Event to include a Sink method? 

Also, I get compiler errors for the sendNext method and sendComplete.

Any help would be great. 
- Thanks

**Comment by alexito4** [comment]
Hi, sorry for the late response but I’m not using this lately. 

The example seems to be working so I’m not sure what can be failing in your project. I will try to update it with the last version of RAC and see if it stills works. 

Cheers.

**Comment by alexito4** [comment]
Got it, is probably related to this https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2442
This is still using an alpha version because is what it was available at that time. 
I will try to update it to use the final version 😉

**Comment by alexito4** [comment]
Should be fixed by 8175766
